preparation:
  paclitaxel:
    type: "drug"  # component type
    mol_wt: 853.906  # drug molecular weight (g/mol)
    target_conc: 3.0   # prefered target concentration (mg/mL)
    mass_weighted: 20.78  # mass weighted (mg)
    solvent: "ethanol"   # solvent
    fractional_range:
      - 0.05
      - 0.4
    levels:
      - 0.05
      - 0.1
      - 0.2
      - 0.4
  cholesterol:
    type: "lipid"
    mol_wt: 386.65
    target_conc: 6.0
    mass_weighted: 46.97
    solvent: "ethanol"
    fractional_range:
      - 0.4
      - 0.9
    levels:
      - 0.4
      - 0.9
  dspc:
    type: "lipid"
    mol_wt: 790.15
    target_conc: 6.0
    mass_weighted: 46.69
    solvent: "ethanol"
    fractional_range:
      - "cholesterol"
      - "dmg-peg_2000"
    levels: null
  dmg-peg_2000:
    type: "lipid"
    mol_wt: 2509.2
    target_conc: 4.0
    mass_weighted: 19.74
    solvent: "ethanol"
    fractional_range:
      - 0.0
      - 0.05
    levels:
      - 0.00
      - 0.015
      - 0.03
      - 0.05
  ethanol:
    type: "solvent"
processing_params:
  org_phase_per_stock: 800  # organic phase per stock solution (uL)
  org_phase_per_well: 50  # organic phase per well (uL)
  total_lipid_conc: 0.2   # total lipid concentration (umol/well)
objectives:
  obj1:
    name: "encapsulation_efficiency"
    goal: "max"
    type: "continuous"
general:
  batch_size: 2
  volume_prec: 0  # number of decimal places after uL
  budget: 10  # maximum allowed measurements
  timeout: 3600 # total allowed time for experiment (seconds)
sheets:
  sa_filename: null
  sheet_name: "test_atlas"  # name of google sheet
  worksheet_name: "Sheet1"  # name of worksheet
  monitor_interval: 5  # sheet monitor interval in seconds
protocol:
  name: "dummy"
  parameter_map:
    paclitaxel: "drug"
    cholesterol: "cholesterol"
    dpsc: "pc"
    dmg-peg-2000: "peglipid"
    ethanol: "ethanol"
  custom_labware_path: "/path/to/file"
  simulation: True  # wheter or not to simulate the opentrons protocol
  ot2_name: null  # ot2 name
  ot2_connection: "wireless"  # ot2 connection type: "wired" or "wireless"
  ot2_wired_ip: "169.254.121.85"  # ot2 wired (usb) address
  ot2_wireless_ip: "192.168.0.168" # ot2 wireless address
